### PR TITLE
Changed names of components. 

### PR DESCRIPTION
**Pull request by ChernykhVyacheslav**
Changes are: 
- Board -> BoardPage , 
- BoardList -> Board, 
- BoardListItem -> BoardColumn, 
- BoardListMenu -> BoardColumnMenu

https://trello.com/c/ro78IqJ0/193-rename-react-components-from-board-page

### CODE REVIEW

**Review by Dchad99 — CHANGES_REQUESTED** [review]
I think there's no need to do it

**Comment by ChernykhVyacheslav** [comment]
> I think there's no need to do it

Right now(without changes from this PR) we have a following situation:
- BoardList component represents Board entity from back-end, though you would expect to represent BoardColumn, that is just wrong naming;
- BoardListItem component represents BoardColumn entity, though you may think it represents item of our list/column, which is Ticket entity, that is confusing naming;
- BoardListMenu was changed to BoardColumnMenu just to match other components;
- There was also an issue of how those components\entities were referred as in the components themself. Like in BoardList component(which is our Board), we had a list of "items", which were our BoardColumns and then there was a boardColor which was a color of BoardColumn and overall more not exactly clear names.

Overall the changes were made to make sure that our component names from front-end match our entity names from back-end and also some consistency in naming was added in the implementation of front-end components themself.

**Comment by Dchad99** [comment]
It doesn't affect on the application.
I agree that fix mismatching with the back-end is quite useful but it is minor changes. As I know these components had other names in the previous version. And now it looks like we have one title then rename it and now came back to the previous version. Is it necessary?

**Comment by ChernykhVyacheslav** [comment]
> It doesn't affect on the application.
> I agree that fix mismatching with the back-end is quite useful but it is minor changes. As I know these components had other names in the previous version. And now it looks like we have one title then rename it and now came back to the previous version. Is it necessary?

Are you asking whether is it necessary to not have a mess of names in our project? Those were not really changed before, so there is no going back to previous version. The names are pretty much the same as you have originally pushed. And I do not understand a point regarding minor change. If a change is minor, it is not necessary? If anyone goes into changing some logic of board page on front-end, they will be very confused because everything there is a mess.

**Comment by Dchad99** [comment]
These components were built regarding the previous version as you asked me after that you changed "names" on the back-end and now you changed "names" on the front-end.
Okay, I will approve this pull request but for me, it isn't clear.
I wonder if there was any need to change the names of components on the back-end and front-end?

**Review by Dchad99 — APPROVED** [review]

**Comment by ChernykhVyacheslav** [comment]
> These components were built regarding the previous version as you asked me after that you changed "names" on the back-end and now you changed "names" on the front-end.
> Okay, I will approve this pull request but for me, it isn't clear.
> I wonder if there was any need to change the names of components on the back-end and front-end?

It was discussed that the names were confusing, so that is the reason for the changes. We have changed BoardList to BoardColumn on back-end, not from BoardList to Board. That is just wrong naming of components on front-end, where component representing our whole Board with list of columns is called BoardList, instead of Board. And other components, as a result, were named in confusing way.

**Review by nelfan — APPROVED** [review]
+1

**Review by jules-n — APPROVED** [review]
+1

**Pull request merged**
